/*=====================================================================
               (c) copyright 1992, the software link inc.
                       all rights reserved

 module name:        vidattr.h
 task name:          install.exe and hdsetup.exe
 creation date:      02/12/92
 revision date:      04/01/92
 author:             mjs
 description:        default video attributes for color systems

======================================================================

mjs 04/01/92	created this module

=======================================================================*/

#define MAIN_ATTR_DEFAULT 0x1f
#define CMD_ATTR_DEFAULT 0x1e
#define ERROR_ATTR_DEFAULT 0x68
#define INVERSE_ATTR_DEFAULT 0x79

