/*=====================================================================
               (c) copyright 1992, the software link inc.
                       all rights reserved

 module name:        insasm.h
 task name:          install.exe
 creation date:      11/20/89
 revision date:      04/01/92
 author:             sah/mjs
 description:        common definitions for insasm.asm

======================================================================

mjs 04/01/92	created this module

=======================================================================*/

extern byte vidattr;

extern void setint21(void);
extern void resetint21(void);

